#!/usr/bin/env node
// Phase 5: finalize — sitemap.xml, robots.txt, and a build report.
//   node scripts/phase5.mjs
import fs from 'node:fs';
import path from 'node:path';
import { DATA_DIR, PUBLIC_DIR, PROGRESS_JSON, REPO_ROOT } from './lib/paths.mjs';
import { JOURNAL_ORDER } from '../src/lib/journals.js';

const PAGES_DIR = path.join(DATA_DIR, 'pages');
const SITE = 'https://www.sgmjournals.org';

// Walk generated entries.
function walk(dir) {
  const out = [];
  for (const name of fs.readdirSync(dir)) {
    const p = path.join(dir, name);
    const st = fs.statSync(p);
    if (st.isDirectory()) out.push(...walk(p));
    else if (name.endsWith('.json')) out.push(p);
  }
  return out;
}

const files = fs.existsSync(PAGES_DIR) ? walk(PAGES_DIR) : [];
const urls = new Set([`${SITE}/`]);
JOURNAL_ORDER.forEach((j) => urls.add(`${SITE}/${j}/`));

const typeCounts = {};
const journalCounts = {};
let stubCount = 0;
let aliasCount = 0;
for (const f of files) {
  let e;
  try { e = JSON.parse(fs.readFileSync(f, 'utf-8')); } catch { continue; }
  const t = e.stub ? 'article-stub' : e.type;
  typeCounts[t] = (typeCounts[t] || 0) + 1;
  if (e.journal) journalCounts[e.journal] = (journalCounts[e.journal] || 0) + 1;
  if (e.alias) { aliasCount++; continue; } // recreated variant page -> canonical is in sitemap, not this
  if (e.stub) { stubCount++; continue; } // keep stubs out of the sitemap (noindex)
  // thin: article with only citation metadata, no body/abstract -> noindex, skip
  if (e.type === 'article' && !e.bodyHtml && !e.abstractHtml) { stubCount++; continue; }
  if (e.canonical) urls.add(e.canonical);
}

// sitemap.xml
function xmlEscape(s) { return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
const sorted = [...urls].sort();
const body = sorted.map((u) => `  <url><loc>${xmlEscape(u)}</loc></url>`).join('\n');
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`;
fs.writeFileSync(path.join(PUBLIC_DIR, 'sitemap.xml'), sitemap);

// robots.txt
const robots = `User-agent: *\nAllow: /\n\nSitemap: ${SITE}/sitemap.xml\n`;
fs.writeFileSync(path.join(PUBLIC_DIR, 'robots.txt'), robots);

// build report
const prog = fs.existsSync(PROGRESS_JSON) ? JSON.parse(fs.readFileSync(PROGRESS_JSON, 'utf-8')) : {};
const redirCount = Object.keys(prog.redirects || {}).length;
const report = `# Build report

Generated by scripts/phase5.mjs.

## Pages
- Total generated entries: ${files.length}
- In sitemap (canonical, indexable full text): ${sorted.length}
- Noindex (citation-only stubs + metadata-only pages): ${stubCount}
- Recreated backlink-variant pages (canonical -> clean URL, excluded from sitemap): ${aliasCount}

## By type
${Object.entries(typeCounts).sort((a, b) => b[1] - a[1]).map(([t, n]) => `- ${t}: ${n}`).join('\n')}

## By journal
${Object.entries(journalCounts).sort((a, b) => b[1] - a[1]).map(([j, n]) => `- ${j}: ${n}`).join('\n')}

## Redirects
- variant -> canonical entries in public/_redirects: ${redirCount}

## pmidlookup
- see src/data/pmidlookup.json (resolved on-site map + PubMed fallback)
`;
fs.writeFileSync(path.join(REPO_ROOT, 'build-report.md'), report);

console.log(`sitemap.xml: ${sorted.length} urls`);
console.log(`robots.txt + build-report.md written`);
console.log(`stubs (excluded from sitemap): ${stubCount}`);
