#!/usr/bin/env node
// Phase 3: resolve pmidlookup endpoints and generate citation-only stub pages
// for high-value uncaptured (in_archive=no) article rows.
//
//   node scripts/phase3.mjs
import fs from 'node:fs';
import path from 'node:path';
import { parseCsv } from './lib/csv.mjs';
import { MANIFEST_CSV, DATA_DIR, PROGRESS_JSON, REPO_ROOT, PUBLIC_DIR } from './lib/paths.mjs';
import { getJournal } from '../src/lib/journals.js';

const PAGES_DIR = path.join(DATA_DIR, 'pages');
const prog = JSON.parse(fs.readFileSync(PROGRESS_JSON, 'utf-8'));
const pmidIndex = prog.pmidIndex || {};
prog.built ||= {};
prog.redirects ||= {};

const rows = parseCsv(MANIFEST_CSV);

// ---- pmidlookup resolution ------------------------------------------------
const resolved = {};            // pmid -> on-site /slug (built article)
const pmidRows = [];            // all pmidlookup rows for the client redirector
for (const r of rows) {
  if (r.page_type !== 'redirect-pmidlookup' || !r.pmid) continue;
  pmidRows.push({ pmid: r.pmid, journal: r.journal || '' });
  const onsite = pmidIndex[r.pmid];
  if (onsite) resolved[r.pmid] = onsite;
}
const journalsWithLookup = [...new Set(pmidRows.map((p) => p.journal).filter(Boolean))];

fs.writeFileSync(
  path.join(REPO_ROOT, 'src', 'data', 'pmidlookup.json'),
  JSON.stringify({ resolved, journals: journalsWithLookup }, null, 0)
);
console.log(`pmidlookup: ${pmidRows.length} rows, ${Object.keys(resolved).length} resolved on-site, ` +
  `${pmidRows.length - Object.keys(resolved).length} fall back to PubMed; journals: ${journalsWithLookup.join(', ')}`);

// ---- citation-only stub pages --------------------------------------------
let stubs = 0;
for (const r of rows) {
  if (r.in_archive === 'yes') continue;
  if (!r.page_type.startsWith('article')) continue;
  const m = (r.canonical_www_url || '').match(/\/([a-z]+)\/content\/([^/]+)\/([^/]+)\/([^/]+)$/);
  if (!m) continue;
  let [, journal, vol, issue, rawPage] = m;
  journal = journal.replace(/^jgv$/, 'vir').replace(/^ijsb$/, 'ijs');
  // strip variant suffixes so the stub lives at the clean canonical
  const page = rawPage.replace(/\.(full\.pdf\+html|full\.pdf|full|abstract|short|long|pdf)$/i, '');
  const slug = `${journal}/content/${vol}/${issue}/${page}`;
  if (!/^[A-Za-z0-9._~+/-]+$/.test(slug)) continue; // only build filesystem-safe slugs

  // redirect any suffixed/variant form of this stub to its clean canonical
  const base = `/${slug}`;
  const rest = `${vol}/${issue}/${page}`;
  for (const v of [
    `/${journal}/content/${rest}.full`, `/${journal}/content/${rest}.abstract`,
    `/${journal}/content/${rest}.short`, `/${journal}/content/${rest}.long`,
    `/${journal}/content/${rest}.full.pdf+html`,
    `/${journal}/cgi/content/full/${rest}`, `/${journal}/cgi/content/abstract/${rest}`,
    `/${journal}/cgi/reprint/${rest}`,
  ]) { if (v !== base) prog.redirects[v] = base; }
  if (rawPage !== page) prog.redirects[`/${journal}/content/${vol}/${issue}/${rawPage}`] = base;

  if (prog.built[slug]) continue; // already have the real page (or another stub)
  const file = path.join(PAGES_DIR, `${slug}.json`);
  if (fs.existsSync(file)) continue;

  const j = getJournal(journal);
  const journalName = j ? j.name : journal;
  const entry = {
    type: 'article',
    slug,
    journal,
    canonical: `https://www.sgmjournals.org/${slug}`,
    stub: true,
    meta: {
      title: `${journalName} ${vol}(${issue}):${page}`,
      authors: [],
      journalTitle: journalName,
      volume: vol, issue, firstpage: page,
      issn: j ? [j.issn] : [],
    },
    abstractHtml: '', bodyHtml: '', referencesHtml: '', affiliationsHtml: '', correspHtml: '',
    pdfPath: null, refdomains: Number(r.rank_refdomains) || 0,
  };
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(entry));
  prog.built[slug] = { type: 'article-stub', ts: Date.now() };
  stubs++;
}
fs.writeFileSync(PROGRESS_JSON, JSON.stringify(prog, null, 2));

// rewrite public/_redirects to include the stub variant redirects
const REDIRECTS_FILE = path.join(PUBLIC_DIR, '_redirects');
const lines = ['# Generated by scripts/ingest.mjs + phase3.mjs — variant -> canonical (in-site).'];
for (const [from, to] of Object.entries(prog.redirects).sort()) lines.push(`${from} ${to} 301`);
fs.writeFileSync(REDIRECTS_FILE, lines.join('\n') + '\n');

console.log(`stubs generated: ${stubs}`);
console.log(`redirects (incl stubs): ${Object.keys(prog.redirects).length}`);
console.log(`total built (incl stubs): ${Object.keys(prog.built).length}`);
